package com.fanfull.db;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;
import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

  private final DaoConfig initInfoDaoConfig;

  private final InitInfoDao initInfoDao;

  public DaoSession(SQLiteDatabase db, IdentityScopeType type,
      Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
          daoConfigMap) {
    super(db);

    initInfoDaoConfig = daoConfigMap.get(InitInfoDao.class).clone();
    initInfoDaoConfig.initIdentityScope(type);

    initInfoDao = new InitInfoDao(initInfoDaoConfig, this);

    registerDao(InitInfo.class, initInfoDao);
  }

  public void clear() {
    initInfoDaoConfig.getIdentityScope().clear();
  }

  public InitInfoDao getInitInfoDao() {
    return initInfoDao;
  }
}
